package com.gallery.phoenix.daogallery;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALBUM".
 */
public class ALBUM {

    private Long id;
    /** Not-null value. */
    private String CreatedDate;
    private String UpdateDate;
    /** Not-null value. */
    private String Name;

    public ALBUM() {
    }

    public ALBUM(Long id) {
        this.id = id;
    }

    public ALBUM(Long id, String CreatedDate, String UpdateDate, String Name) {
        this.id = id;
        this.CreatedDate = CreatedDate;
        this.UpdateDate = UpdateDate;
        this.Name = Name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCreatedDate() {
        return CreatedDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedDate(String CreatedDate) {
        this.CreatedDate = CreatedDate;
    }

    public String getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(String UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

}
