package com.gallery.phoenix.daogallery;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gallery.phoenix.daogallery.ALBUM;
import com.gallery.phoenix.daogallery.PIC;

import com.gallery.phoenix.daogallery.ALBUMDao;
import com.gallery.phoenix.daogallery.PICDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aLBUMDaoConfig;
    private final DaoConfig pICDaoConfig;

    private final ALBUMDao aLBUMDao;
    private final PICDao pICDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aLBUMDaoConfig = daoConfigMap.get(ALBUMDao.class).clone();
        aLBUMDaoConfig.initIdentityScope(type);

        pICDaoConfig = daoConfigMap.get(PICDao.class).clone();
        pICDaoConfig.initIdentityScope(type);

        aLBUMDao = new ALBUMDao(aLBUMDaoConfig, this);
        pICDao = new PICDao(pICDaoConfig, this);

        registerDao(ALBUM.class, aLBUMDao);
        registerDao(PIC.class, pICDao);
    }
    
    public void clear() {
        aLBUMDaoConfig.getIdentityScope().clear();
        pICDaoConfig.getIdentityScope().clear();
    }

    public ALBUMDao getALBUMDao() {
        return aLBUMDao;
    }

    public PICDao getPICDao() {
        return pICDao;
    }

}
