package com.gallery.phoenix.daogallery;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PIC".
 */
public class PIC {

    private Long id;
    /** Not-null value. */
    private String Uri;

    public PIC() {
    }

    public PIC(Long id) {
        this.id = id;
    }

    public PIC(Long id, String Uri) {
        this.id = id;
        this.Uri = Uri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUri() {
        return Uri;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUri(String Uri) {
        this.Uri = Uri;
    }

}
